shop419/authentication/urls.py
from django.urls import path
from . import views # importing the views from the app to access the functions


urlpatterns = [
    path('login',views.Login.as_view(), name='signin'),
    path('register',views.UserRegister.as_view(), name='signup'),


]

shop419/myapp/urls.py
from django.urls import path
from . import views # importing the views from the myapp to access the functions

from . views import homeView, aboutView, AddProduct, ProductDetails, UpdateProduct, DeleteProduct

urlpatterns = [
    path('', views.homeView, name='home'),
    path("about", views.aboutView, name="aboutpage"),
    path("products", views.ProductList.as_view(), name="products"),

    path('products/add', AddProduct.as_view(), name='add_prod'),
    path('products/<int:pk>', ProductDetails.as_view(), name='prod_details'),     # dynamic urlpattern
    path('products/edit/<int:pk>', UpdateProduct.as_view(), name='edit_prod'),
    path('products/del/<int:pk>', DeleteProduct.as_view(), name='del_prod')
]

shop419/shop419/urls.py
from django.contrib import admin
from django.urls import path,include

# adding this line to support hosting of static files
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),   # to include the paths configured in the app here 
    path('auth/', include('authentication.urls')),   # login , register we will create
    path('auth/', include('django.contrib.auth.urls')),   # logout path will take from django inbuilt contrib
]


# the following line allows us to use the given media path during development
if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shop419/authentication/models.py
from django.db import models

# Create your models here.

shop419/myapp/models.py
from django.db import models

# Create your models here.
# Automatic ORM(Object Relational Mapping) methods are already pre-designed in this class

class Product(models.Model):
    # list out all the object variables below and initialize with certain classes.
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField(null=False)
    desc = models.TextField(null=True)
    pic  = models.ImageField(upload_to="products/", null=False)
    stock = models.PositiveBigIntegerField(default=1)

shop419/authentication/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from django.views.generic import CreateView

# importing django.contrib.auth usercreation forms
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.views import LoginView


# Create your views here.

class UserRegister(CreateView):
    form_class = UserCreationForm  # specifying the way in which the form object should be built
    template_name = 'register.html'
    success_url = reverse_lazy('signin') # url name to redirect to once signup is done

class Login(LoginView):
    template_name = "login.html"

shop419/myapp/views.py
from django.shortcuts import render
from .models import Product

from django.urls import reverse_lazy

# to help load the template files
from django.template import loader

# to help return an http response to the user for any given request
from django.http import HttpResponse

# importing the genereic class based views for CRUD operations
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView




# Create your views here.

def homeView(request):
    products = Product.objects.all()   # its like select * from Product

    # Creating a context dictionary to be used to render the template with info
    context = {
        'product_list' : products, # the key we create here will be available in template design in home.html

        'current_page' : 'home'
    }
    template = loader.get_template("home.html")
    return HttpResponse(template.render(context, request))

def aboutView(request):

    context = {
        'current_page' : 'about',
        "name" : "Kenson",
        "students" : ["Deepak","Surya","Dattatri"],

       'slept' : True

    }
    template=loader.get_template("about.html")
    return HttpResponse(template.render(context, request))

class ProductList(ListView):
    model = Product
    template_name = 'products.html'



# Create
class AddProduct(CreateView):
    model = Product
    fields = ['name', 'price', 'desc', 'pic', 'stock']
    template_name = 'addProduct.html'
    success_url = reverse_lazy('home')

# Read
class ProductDetails(DetailView):
    model = Product
    template_name = 'prod_details.html'
    context_object_name = 'prod'

# Update
from django.urls import reverse

class UpdateProduct(UpdateView):
    model = Product
    fields = '__all__'
    template_name = 'editProduct.html'

    def get_success_url(self):
        return reverse('prod_details', kwargs = {'pk' : self.object.pk})
    
# Delete 
class DeleteProduct(DeleteView):
    model = Product
    template_name = 'delProduct.html'
    success_url = reverse_lazy('home')

shop419/authentication/templates/login.html
{% extends 'base.html'%}
{% load static %}
{% block title %}
Sign in
{% endblock %}

{% block content %}
<form method="post">    
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Sign in</button>
</form>
{% endblock %}

<!-- post method will hide the username and password in the url, get request will show the credentials in the url -->

shop419/authentication/templates/register.html
{% extends 'base.html'%}
{% load static %}
{% block title %}
Sign up
{% endblock %}

{% block content %}
<form method="post">    
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Sign up</button>
</form>
{% endblock %}

<!-- post method will hide the username and password in the url, get request will show the credentials in the -->

shop419/myapp/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
About the store 
{% endblock %}


{% block content %}
    <div>
        <p> Hi This is my about page</p>
    </div>
    
    {{name}}

    <!-- loops -->
     <ul>
        {% for student in students %}
        <ul>
            <li>{{ student }}</li>
        </ul>
        {% endfor %}
     </ul>


     <!-- Conditionals -->
       {% if slept %}
       I slept
       {% else %}
       Did not sleep
       {% endif %}

{% endblock %}

shop419/myapp/templates/addProduct.html
{% extends 'base.html' %}
{% block title %}
Add Product
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group">
        <label for="id_name">Name:</label>
        {{ form.name }}
    </div>
    <div class="form-group">
        <label for="id_price">Price</label>
        {{ form.price }}
    </div>
    <div class="form-group">
        <label for="id_desc">Description</label>
        {{ form.desc }}
    </div>
    <div class="form-group">
        <label for="id_stock">Stock</label>
        {{ form.stock }}
    </div>
    <div class="form-group">
        <label for="id_pic">Picture</label>
        {{ form.pic }}
    </div>
    <button type="submit" class="btn btn-warning">Add Product</button>

</form>

{% endblock %}

shop419/myapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
   
      {% block title%}
      {% endblock %}
    </title>

    <!-- 1.link for bootstrap CSS-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">

    <!-- 2.linking the static css files -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- link for bootstrap icons-->
    <link rel="shortcut icon" href="{% static 'images/icons/shop-logo1.png' %}" type="image/x-icon">
</head>
<body>
    <header>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Nike</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link {% if current_page == 'home' %}border disabled{% else %}active{% endif %}" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if current_page == 'aboutpage' %}border disabled{% else %}active{% endif %}" href="{% url 'aboutpage' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if current_page == 'products' %}border disabled{% else %}active{% endif %}" href="{% url 'products' %}">Products</a>
              </li>

              {% if user.is_authenticated %}
                   {% if user.is_superuser %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'add_prod' %}">Add Product</a>
                      </li>
                   {% else %}
                      <li class="nav-item">
                        <a class="nav-link" href="">My cart</a>
                      </li>
                   {% endif %}
              {% endif %}
              <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li> -->

            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>

            <ul class="navbar-nav">

            {% if user.is_authenticated %}
              <li class="nav-item">
                <form action="{% url 'logout' %}" method="post">
                  {% csrf_token %}
                  <button class="nav-link">Logout</button>
                </form>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="btn btn-warning" href="{% url 'signin' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="btn btn-outline-success" href="{% url 'signup' %}">Sign up</a>
              </li>

            {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer class="py-5">
        <div class="row">
          <div class="col-6 col-md-2 mb-3">
            <h5>Section</h5>
            <ul class="nav flex-column">
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
            </ul>
          </div>
    
          <div class="col-6 col-md-2 mb-3">
            <h5>Section</h5>
            <ul class="nav flex-column">
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
            </ul>
          </div>
    
          <div class="col-6 col-md-2 mb-3">
            <h5>Section</h5>
            <ul class="nav flex-column">
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
            </ul>
          </div>
    
          <div class="col-md-5 offset-md-1 mb-3">
            <form>
              <h5>Subscribe to our newsletter</h5>
              <p>Monthly digest of what's new and exciting from us.</p>
              <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                <label for="newsletter1" class="visually-hidden">Email address</label>
                <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
                <button class="btn btn-primary" type="button">Subscribe</button>
              </div>
            </form>
          </div>
        </div>
        <p style="text-align: center;">© 2025 Company, Inc. All rights reserved.</p>
    
        <!-- <div class="d-flex flex-column flex-sm-row justify-content-between py-2 mx-4 border-top">
          <p style="text-align: center;">© 2025 Company, Inc. All rights reserved.</p>
          <ul class="list-unstyled d-flex">
            <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
            <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
            <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
          </ul>
        </div> -->
      </footer>
  
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
         
  </body>
  </html>

shop419/myapp/templates/delProduct.html
{% extends 'base.html' %}
{% block title %}
Delete Product
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}
    <button type="submit" class="btn btn-warning">Delete Product</button>

</form>

{% endblock %}

shop419/myapp/templates/editProduct.html
{% extends 'base.html' %}
{% block title %}
Edit Product
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}
    <button type="submit" class="btn btn-warning">Edit Product</button>

</form>

{% endblock %}

shop419/myapp/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Home
{% endblock %}


{% block content %}

        <div id="carouselExample" class="carousel slide">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{% static 'images/carousal/domino-studio.jpg' %}" class="d-block w-100" alt="..." style="height:600px;">
              </div>
              <div class="carousel-item">
                <img src="{% static 'images/carousal/joseph-barrientos.jpg' %}" class="d-block w-100" alt="..." style="height:600px;">
              </div>
              <div class="carousel-item">
                <img src="{% static 'images/carousal/maksim-larin.jpg' %}" class="d-block w-100" alt="..." style="height:600px;">
              </div>
              <div class="carousel-item">
                <img src="{% static 'images/carousal/jakob-owens.jpg' %}" class="d-block w-100" alt="..." style="height:600px;">
              </div>
              <div class="carousel-item">
                <img src="{% static 'images/carousal/lefteris-kallergis.jpg' %}" class="d-block w-100" alt="..." style="height:600px;">
              </div>
              <div class="carousel-item">
                <img src="{% static 'images/carousal/paul-volkmer.jpg' %}" class="d-block w-100" alt="..." style="height:600px;">
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>

          <br>
          <br>

          <div class="container-fluid">
            <table class="table" data-bs-theme="dark" bg-dark>
                <thead>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Pic path</th>
                    <th>Thumbnail</th>
                    <th>Stock</th>
                    <th>Description</th>
                    <th></th>
                </thead>
                <tbody>
                {% for product in product_list %}
                    <tr>
                        <td>{{product.id}}</td>
                        <td>{{product.name}}</td>
                        <td>{{product.price}}</td>
                        <td>{{product.pic}}</td>
                        <td><img src="{{product.pic}}" height="20px" alt=""></td>
                        <td>{{product.stock}}</td>
                        <td>{{product.desc}}</td>
                        <td><button class="btn btn-primary">Add to Cart</button></td>
                    </tr>
                {% endfor %}
                </tbody>
          
            </table>
        </div>


    {% endblock %}
   

shop419/myapp/templates/prod_details.html
{% extends 'base.html' %}


{% block title %}
{{ prod.name }}
{% endblock %}


{% block content %}
<div class="row">
    <div class="col-sm-6 ">
        <img src="{{prod.pic.url}}" class="w-100 h-100" alt="">
    </div>
    <div class="col-sm-6">
        <div class="row">
            <h1>{{ prod.name }}</h1>
            <p>Rs.{{ prod.price }}</p>
        </div>
        <div class="row">
            {% if user.is_staff %}
            <a href="" class="btn btn-secondary">Edit Product</a>
            {% else %}
            <a href="" class="btn btn-secondary">Add to Cart</a>
            {% endif %}
        </div>

    </div>

</div>
{% endblock %}

shop419/myapp/templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Products
{% endblock %}

{% block content %}

<section id="products">
    <div class="prod-container">
      {% for p in product_list %}                                      <!--product_list is defined in djangos thing-->
      <!-- Code for single card starts here -->
      <div class="card">
              
              <a href="{% url 'prod_details' p.pk %}">                            <!--p_details is defined in urls.py-->       
                <img src="{{p.pic}}" alt="" width="200px" height="200px">
              </a>
  
          <div class="card-text">
                <h5 class="card-title">{{p.name}}</h5>

                <h5>Price : ₹<ins>{{p.price}}</ins></h5>

  
                <span style="color: black;">Qty:{{p.stock}}</span>

  
                <a href="" class="btn btn-primary">Add To Cart</a>
  
              
          </div>
  
      </div>
      <!-- Code for a single card ends here -->
      {% endfor %}
    </div>
    
    </section>
  
  
  {% endblock %}